version: '3.7'
services:
  game_library:
    build: .
    ports:
    - target: 9000
      published: 9000
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - game_library
