version: 2 
jobs: 
  build: 
    
    working_directory: ~/game_library 

    docker: 
      - image: circleci/openjdk:8-jdk-stretch 
    
    steps: 

      - checkout # check out source code to working directory

      - restore_cache: 
          key: game_library-{{ checksum "pom.xml" }}
          
      - run: mvn dependency:go-offline # gets the project dependencies
     
      
      - run: mvn package 
     
     
      - run:
          name: Clone Repo 
          command: ssh -o StrictHostKeyChecking=no "git clone https://github.com/psilva12/Fundamental_Project.git"
      - run:
          name: Deploy Application
          command: ssh -o StrictHostKeyChecking=no "cd ~/game_library && npm run serve"

