version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Tests can run here!"
  deploy:
    machine:
      enabled: true
    steps:
       working_directory: ~/Fundamental_Project
       docker:
          - image: circleci/openjdk:8-jdk-stretch
       - restore_cache: 
            key: Fundamental_Project-{{ checksum "pom.xml" }}
       - run: mvn dependency:go-offline # gets the project dependencies
 
       - run: mvn package 
      
       - run:
           name: Install Java
           command: sudo apt-get install -y openjdk-8-jdk
       - run:
           name: Install Spring boot
           command: sdk install -y springboot
          
      
       - run:
           name: Clone Repo & Install Application Dependencies
           command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/psilva12/Fundamental_Project && npm install"
       - run:
           name: Deploy Application
           command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project && mvn run serve"
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

