jobs: 
  build: 
    
    working_directory: ~/Fundamental_Project
    docker: 
      - image: circleci/openjdk:8-jdk-stretch 
    
    steps: 
      - checkout # check out source code to working directory
      - restore_cache: 
          key: Fundamental_Project-{{ checksum "pom.xml" }}
          
      - run: mvn dependency:go-offline # gets the project dependencies
 
      - run: mvn package 
      
      - run:
          name: Install Spring boot
          command: sdk install -y springboot
          
      
      - run:
          name: Clone Repo & Install Application Dependencies
          command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/psilva12/Fundamental_Project && npm install"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project && mvn run serve"

